# Generated by Django 4.0.1 on 2022-02-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodectdetails',
            name='image',
            field=models.ImageField(blank=True, default='static/image/default.png', null=True, upload_to=''),
        ),
    ]
