# Generated by Django 4.0.1 on 2022-02-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCRUD', '0002_alter_prodectdetails_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodectdetails',
            name='image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
