# Generated by Django 4.0.1 on 2022-02-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCRUD', '0004_alter_prodectdetails_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodectdetails',
            name='image',
        ),
    ]
