# Generated by Django 4.0.1 on 2022-02-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCRUD', '0005_remove_prodectdetails_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodectdetails',
            name='abc',
            field=models.CharField(default=2, max_length=225),
            preserve_default=False,
        ),
    ]
