# Generated by Django 4.0.1 on 2022-02-17 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCRUD', '0006_prodectdetails_abc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodectdetails',
            name='abc',
        ),
    ]
